parameters:
  OuterApiName:
stages:
- stage: Build
  jobs:
  - template: ../../pipeline-templates/job/code-build.yml
    parameters:
      SonarCloudProjectKey: SkillsFundingAgency_das-apim-endpoints_${{ parameters.OuterApiName }}
      TargetProjects: |
        src/${{ parameters.OuterApiName }}/**/*.csproj
        src/Shared/SFA.DAS.SharedOuterApi.UnitTests/SFA.DAS.SharedOuterApi.UnitTests.csproj
      UnitTestProjects: |
        src/${{ parameters.OuterApiName }}/**/*UnitTests.csproj
        src/Shared/SFA.DAS.SharedOuterApi.UnitTests/SFA.DAS.SharedOuterApi.UnitTests.csproj
      AcceptanceTestProjects: 'src/${{ parameters.OuterApiName }}/**/*AcceptanceTests.csproj'
      PublishProject: 'src/${{ parameters.OuterApiName }}/SFA.DAS.${{ parameters.OuterApiName }}.Api/SFA.DAS.${{ parameters.OuterApiName }}.Api.csproj'

- stage: Deploy_AT
  dependsOn: Build
  displayName: Deploy to AT
  variables:
  - group: DevTest Management Resources
  - group: AT DevTest Shared Resources
  - group: AT das-apim-endpoints
  jobs:
  - template: ../../pipeline-templates/job/deploy.yml
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-CDS
      Environment: AT
      SchemaFilePath: $(${{ parameters.OuterApiName }}OuterApiSchemaFilePath)
      DeploymentName: Deploy_${{ parameters.OuterApiName }}
      AADGroupObjectIdArray: $(AdminAADGroupObjectId),$(DevAADGroupObjectId)
      AppServiceName: $(${{ parameters.OuterApiName }}OuterApiAppServiceName)
      CustomHostName: $(${{ parameters.OuterApiName }}OuterApiCustomHostname)
      AppServiceKeyVaultCertificateName: $(${{ parameters.OuterApiName }}OuterApiKeyVaultCertificateName)
      ConfigNames: $(${{ parameters.OuterApiName }}OuterApiConfigNames)
      DeploymentPackagePath: $(Pipeline.Workspace)/ApimEndpointsArtifacts/SFA.DAS.${{ parameters.OuterApiName }}.Api.zip
      ApiVersionSetName: $(${{ parameters.OuterApiName }}OuterApiVersionSetName)
      ApiPath: $(${{ parameters.OuterApiName }}OuterApiPath)
      ApiBaseUrl: $(${{ parameters.OuterApiName }}OuterApiBaseUrl)
      ProductId: $(${{ parameters.OuterApiName }}ProductId)
      ApplicationIdentifierUri: $(${{ parameters.OuterApiName }}OuterApiIdentifierUri)

- stage: Deploy_TEST
  dependsOn: Build
  displayName: Deploy to TEST
  variables:
  - group: DevTest Management Resources
  - group: TEST DevTest Shared Resources
  - group: TEST das-apim-endpoints
  jobs:
  - template: ../../pipeline-templates/job/deploy.yml
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-CDS
      Environment: TEST
      SchemaFilePath: $(${{ parameters.OuterApiName }}OuterApiSchemaFilePath)
      DeploymentName: Deploy_${{ parameters.OuterApiName }}
      AADGroupObjectIdArray: $(AdminAADGroupObjectId),$(DevAADGroupObjectId)
      AppServiceName: $(${{ parameters.OuterApiName }}OuterApiAppServiceName)
      CustomHostName: $(${{ parameters.OuterApiName }}OuterApiCustomHostname)
      AppServiceKeyVaultCertificateName: $(${{ parameters.OuterApiName }}OuterApiKeyVaultCertificateName)
      ConfigNames: $(${{ parameters.OuterApiName }}OuterApiConfigNames)
      DeploymentPackagePath: $(Pipeline.Workspace)/ApimEndpointsArtifacts/SFA.DAS.${{ parameters.OuterApiName }}.Api.zip
      ApiVersionSetName: $(${{ parameters.OuterApiName }}OuterApiVersionSetName)
      ApiPath: $(${{ parameters.OuterApiName }}OuterApiPath)
      ApiBaseUrl: $(${{ parameters.OuterApiName }}OuterApiBaseUrl)
      ProductId: $(${{ parameters.OuterApiName }}ProductId)
      ApplicationIdentifierUri: $(${{ parameters.OuterApiName }}OuterApiIdentifierUri)

- stage: Deploy_TEST2
  dependsOn: Build
  displayName: Deploy to TEST2
  variables:
  - group: DevTest Management Resources
  - group: TEST2 DevTest Shared Resources
  - group: TEST2 das-apim-endpoints
  jobs:
  - template: ../../pipeline-templates/job/deploy.yml
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-CDS
      Environment: TEST2
      SchemaFilePath: $(${{ parameters.OuterApiName }}OuterApiSchemaFilePath)
      DeploymentName: Deploy_${{ parameters.OuterApiName }}
      AADGroupObjectIdArray: $(AdminAADGroupObjectId),$(DevAADGroupObjectId)
      AppServiceName: $(${{ parameters.OuterApiName }}OuterApiAppServiceName)
      CustomHostName: $(${{ parameters.OuterApiName }}OuterApiCustomHostname)
      AppServiceKeyVaultCertificateName: $(${{ parameters.OuterApiName }}OuterApiKeyVaultCertificateName)
      ConfigNames: $(${{ parameters.OuterApiName }}OuterApiConfigNames)
      DeploymentPackagePath: $(Pipeline.Workspace)/ApimEndpointsArtifacts/SFA.DAS.${{ parameters.OuterApiName }}.Api.zip
      ApiVersionSetName: $(${{ parameters.OuterApiName }}OuterApiVersionSetName)
      ApiPath: $(${{ parameters.OuterApiName }}OuterApiPath)
      ApiBaseUrl: $(${{ parameters.OuterApiName }}OuterApiBaseUrl)
      ProductId: $(${{ parameters.OuterApiName }}ProductId)
      ApplicationIdentifierUri: $(${{ parameters.OuterApiName }}OuterApiIdentifierUri)

- stage: Deploy_PP
  dependsOn: Build
  displayName: Deploy to PP
  variables:
  - group: PREPROD Management Resources
  - group: PREPROD Shared Resources
  - group: PREPROD das-apim-endpoints
  jobs:
  - template: ../../pipeline-templates/job/deploy.yml
    parameters:
      ServiceConnection: SFA-DIG-PreProd-ARM
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-FCS
      Environment: PP
      SchemaFilePath: $(${{ parameters.OuterApiName }}OuterApiSchemaFilePath)
      DeploymentName: Deploy_${{ parameters.OuterApiName }}
      AADGroupObjectIdArray: $(AdminAADGroupObjectId),$(DevAADGroupObjectId)
      AppServiceName: $(${{ parameters.OuterApiName }}OuterApiAppServiceName)
      CustomHostName: $(${{ parameters.OuterApiName }}OuterApiCustomHostname)
      AppServiceKeyVaultCertificateName: $(${{ parameters.OuterApiName }}OuterApiKeyVaultCertificateName)
      ConfigNames: $(${{ parameters.OuterApiName }}OuterApiConfigNames)
      DeploymentPackagePath: $(Pipeline.Workspace)/ApimEndpointsArtifacts/SFA.DAS.${{ parameters.OuterApiName }}.Api.zip
      ApiVersionSetName: $(${{ parameters.OuterApiName }}OuterApiVersionSetName)
      ApiPath: $(${{ parameters.OuterApiName }}OuterApiPath)
      ApiBaseUrl: $(${{ parameters.OuterApiName }}OuterApiBaseUrl)
      ProductId: $(${{ parameters.OuterApiName }}ProductId)
      ApplicationIdentifierUri: $(${{ parameters.OuterApiName }}OuterApiIdentifierUri)

- stage: Deploy_PROD
  dependsOn: Build
  displayName: Deploy to PROD
  variables:
  - group: PROD Management Resources
  - group: PROD Shared Resources
  - group: PROD das-apim-endpoints
  jobs:
  - template: ../../pipeline-templates/job/deploy.yml
    parameters:
      ServiceConnection: SFA-DIG-Prod-ARM
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-FCS
      Environment: PROD
      SchemaFilePath: $(${{ parameters.OuterApiName }}OuterApiSchemaFilePath)
      DeploymentName: Deploy_${{ parameters.OuterApiName }}
      AppServiceName: $(${{ parameters.OuterApiName }}OuterApiAppServiceName)
      CustomHostName: $(${{ parameters.OuterApiName }}OuterApiCustomHostname)
      AppServiceKeyVaultCertificateName: $(${{ parameters.OuterApiName }}OuterApiKeyVaultCertificateName)
      ConfigNames: $(${{ parameters.OuterApiName }}OuterApiConfigNames)
      DeploymentPackagePath: $(Pipeline.Workspace)/ApimEndpointsArtifacts/SFA.DAS.${{ parameters.OuterApiName }}.Api.zip
      ApiVersionSetName: $(${{ parameters.OuterApiName }}OuterApiVersionSetName)
      ApiPath: $(${{ parameters.OuterApiName }}OuterApiPath)
      ApiBaseUrl: $(${{ parameters.OuterApiName }}OuterApiBaseUrl)
      ProductId: $(${{ parameters.OuterApiName }}ProductId)
      ApplicationIdentifierUri: $(${{ parameters.OuterApiName }}OuterApiIdentifierUri)

- stage: Deploy_MO
  dependsOn: Build
  displayName: Deploy to MO
  variables:
  - group: MO Management Resources
  - group: MO Shared Resources
  - group: MO das-apim-endpoints
  jobs:
  - template: ../../pipeline-templates/job/deploy.yml
    parameters:
      ServiceConnection: SFA-ASM-ModelOffice-ARM
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-FCS
      Environment: MO
      SchemaFilePath: $(${{ parameters.OuterApiName }}OuterApiSchemaFilePath)
      DeploymentName: Deploy_${{ parameters.OuterApiName }}
      AppServiceName: $(${{ parameters.OuterApiName }}OuterApiAppServiceName)
      CustomHostName: $(${{ parameters.OuterApiName }}OuterApiCustomHostname)
      AppServiceKeyVaultCertificateName: $(${{ parameters.OuterApiName }}OuterApiKeyVaultCertificateName)
      ConfigNames: $(${{ parameters.OuterApiName }}OuterApiConfigNames)
      DeploymentPackagePath: $(Pipeline.Workspace)/ApimEndpointsArtifacts/SFA.DAS.${{ parameters.OuterApiName }}.Api.zip
      ApiVersionSetName: $(${{ parameters.OuterApiName }}OuterApiVersionSetName)
      ApiPath: $(${{ parameters.OuterApiName }}OuterApiPath)
      ApiBaseUrl: $(${{ parameters.OuterApiName }}OuterApiBaseUrl)
      ProductId: $(${{ parameters.OuterApiName }}ProductId)
      ApplicationIdentifierUri: $(${{ parameters.OuterApiName }}OuterApiIdentifierUri)

- stage: Deploy_DEMO
  dependsOn: Build
  displayName: Deploy to DEMO
  variables:
  - group: DevTest Management Resources
  - group: DEMO DevTest Shared Resources
  - group: DEMO das-apim-endpoints
  jobs:
  - template: ../../pipeline-templates/job/deploy.yml
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-CDS
      Environment: DEMO
      SchemaFilePath: $(${{ parameters.OuterApiName }}OuterApiSchemaFilePath)
      DeploymentName: Deploy_${{ parameters.OuterApiName }}
      AADGroupObjectIdArray: $(AdminAADGroupObjectId),$(DevAADGroupObjectId)
      AppServiceName: $(${{ parameters.OuterApiName }}OuterApiAppServiceName)
      CustomHostName: $(${{ parameters.OuterApiName }}OuterApiCustomHostname)
      AppServiceKeyVaultCertificateName: $(${{ parameters.OuterApiName }}OuterApiKeyVaultCertificateName)
      ConfigNames: $(${{ parameters.OuterApiName }}OuterApiConfigNames)
      DeploymentPackagePath: $(Pipeline.Workspace)/ApimEndpointsArtifacts/SFA.DAS.${{ parameters.OuterApiName }}.Api.zip
      ApiVersionSetName: $(${{ parameters.OuterApiName }}OuterApiVersionSetName)
      ApiPath: $(${{ parameters.OuterApiName }}OuterApiPath)
      ApiBaseUrl: $(${{ parameters.OuterApiName }}OuterApiBaseUrl)
      ProductId: $(${{ parameters.OuterApiName }}ProductId)
      ApplicationIdentifierUri: $(${{ parameters.OuterApiName }}OuterApiIdentifierUri)
