trigger: none
pr: none

variables:
- group: Release Management Resources
- group: RELEASE das-apim-endpoints

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.3.14
    endpoint: GitHub (SFA)
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/4.4.1
    endpoint: GitHub (SFA)
  pipelines:
  - pipeline: das-apim-endpoints-build
    project: Digital Apprenticeship Service
    source: das-apim-endpoints (build)
    branch: master
  - pipeline: das-employer-config
    project: Digital Apprenticeship Service
    source: das-employer-config
    branch: master

stages:
- stage: Deploy_AT
  dependsOn: []  
  displayName: Deploy to AT
  variables:
  - group: DevTest Management Resources
  - group: AT DevTest Shared Resources
  - group: AT das-apim-endpoints
  jobs:
  - template: ../pipeline-templates/job/arm-deploy.yml
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-CDS
      Environment: AT

  - template: ../pipeline-templates/job/deploy-api.yml
    parameters:
      DeploymentName: Deploy_FindApprenticeshipTraining
      Environment: AT
      ServiceConnection: SFA-DAS-DevTest-ARM
      AppServiceName: $(FindApprenticeshipTrainingOuterApiAppServiceName)
      DeploymentPackagePath: $(Pipeline.Workspace)/das-apim-endpoints-build/ApimEndpointsArtifacts/SFA.DAS.FindApprenticeshipTraining.Api.zip
      ApiVersionSetName: $(FindApprenticeshipTrainingOuterApiVersionSetName)
      ApiPath: $(FindApprenticeshipTrainingOuterApiPath)
      ApiBaseUrl: $(FindApprenticeshipTrainingOuterApiBaseUrl)
      ProductId: $(FindApprenticeshipTrainingProductId)
      ApplicationIdentifierUri: $(FindApprenticeshipTrainingOuterApiIdentifierUri)
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-CDS

- stage: Deploy_TEST
  dependsOn: []  
  displayName: Deploy to TEST
  variables:
  - group: DevTest Management Resources
  - group: TEST DevTest Shared Resources
  - group: TEST das-apim-endpoints
  jobs:
  - template: ../pipeline-templates/job/arm-deploy.yml
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-CDS
      Environment: TEST

  - template: ../pipeline-templates/job/deploy-api.yml
    parameters:
      DeploymentName: Deploy_FindApprenticeshipTraining
      Environment: TEST
      ServiceConnection: SFA-DAS-DevTest-ARM
      AppServiceName: $(FindApprenticeshipTrainingOuterApiAppServiceName)
      DeploymentPackagePath: $(Pipeline.Workspace)/das-apim-endpoints-build/ApimEndpointsArtifacts/SFA.DAS.FindApprenticeshipTraining.Api.zip
      ApiVersionSetName: $(FindApprenticeshipTrainingOuterApiVersionSetName)
      ApiPath: $(FindApprenticeshipTrainingOuterApiPath)
      ApiBaseUrl: $(FindApprenticeshipTrainingOuterApiBaseUrl)
      ProductId: $(FindApprenticeshipTrainingProductId)
      ApplicationIdentifierUri: $(FindApprenticeshipTrainingOuterApiIdentifierUri)
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-CDS

- stage: Deploy_TEST2
  dependsOn: []
  displayName: Deploy to TEST2
  variables:
  - group: DevTest Management Resources
  - group: TEST2 DevTest Shared Resources
  - group: TEST2 das-apim-endpoints
  jobs:
  - template: ../pipeline-templates/job/arm-deploy.yml
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-CDS
      Environment: TEST2

  - template: ../pipeline-templates/job/deploy-api.yml
    parameters:
      DeploymentName: Deploy_FindApprenticeshipTraining
      Environment: TEST2
      ServiceConnection: SFA-DAS-DevTest-ARM
      AppServiceName: $(FindApprenticeshipTrainingOuterApiAppServiceName)
      DeploymentPackagePath: $(Pipeline.Workspace)/das-apim-endpoints-build/ApimEndpointsArtifacts/SFA.DAS.FindApprenticeshipTraining.Api.zip
      ApiVersionSetName: $(FindApprenticeshipTrainingOuterApiVersionSetName)
      ApiPath: $(FindApprenticeshipTrainingOuterApiPath)
      ApiBaseUrl: $(FindApprenticeshipTrainingOuterApiBaseUrl)
      ProductId: $(FindApprenticeshipTrainingProductId)
      ApplicationIdentifierUri: $(FindApprenticeshipTrainingOuterApiIdentifierUri)
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-CDS

- stage: Deploy_PP
  dependsOn: []
  displayName: Deploy to PP
  variables:
  - group: PREPROD Management Resources
  - group: PREPROD Shared Resources
  - group: PREPROD das-apim-endpoints
  jobs:
  - template: ../pipeline-templates/job/arm-deploy.yml
    parameters:
      ServiceConnection: SFA-DIG-PreProd-ARM
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-FCS
      Environment: PP

  - template: ../pipeline-templates/job/deploy-api.yml
    parameters:
      DeploymentName: Deploy_FindApprenticeshipTraining
      Environment: PP
      ServiceConnection: SFA-DIG-PreProd-ARM
      AppServiceName: $(FindApprenticeshipTrainingOuterApiAppServiceName)
      DeploymentPackagePath: $(Pipeline.Workspace)/das-apim-endpoints-build/ApimEndpointsArtifacts/SFA.DAS.FindApprenticeshipTraining.Api.zip
      ApiVersionSetName: $(FindApprenticeshipTrainingOuterApiVersionSetName)
      ApiPath: $(FindApprenticeshipTrainingOuterApiPath)
      ApiBaseUrl: $(FindApprenticeshipTrainingOuterApiBaseUrl)
      ProductId: $(FindApprenticeshipTrainingProductId)
      ApplicationIdentifierUri: $(FindApprenticeshipTrainingOuterApiIdentifierUri)
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-FCS

- stage: Deploy_PROD
  dependsOn: []
  displayName: Deploy to PROD
  variables:
  - group: PROD Management Resources
  - group: PROD Shared Resources
  - group: PROD das-apim-endpoints
  jobs:
  - template: ../pipeline-templates/job/arm-deploy.yml
    parameters:
      ServiceConnection: SFA-DIG-Prod-ARM
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-FCS
      Environment: PROD

  - template: ../pipeline-templates/job/deploy-api.yml
    parameters:
      DeploymentName: Deploy_FindApprenticeshipTraining
      Environment: PROD
      ServiceConnection: SFA-DIG-Prod-ARM
      AppServiceName: $(FindApprenticeshipTrainingOuterApiAppServiceName)
      DeploymentPackagePath: $(Pipeline.Workspace)/das-apim-endpoints-build/ApimEndpointsArtifacts/SFA.DAS.FindApprenticeshipTraining.Api.zip
      ApiVersionSetName: $(FindApprenticeshipTrainingOuterApiVersionSetName)
      ApiPath: $(FindApprenticeshipTrainingOuterApiPath)
      ApiBaseUrl: $(FindApprenticeshipTrainingOuterApiBaseUrl)
      ProductId: $(FindApprenticeshipTrainingProductId)
      ApplicationIdentifierUri: $(FindApprenticeshipTrainingOuterApiIdentifierUri)
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-FCS

- stage: Deploy_MO
  dependsOn: []
  displayName: Deploy to MO
  variables:
  - group: MO Management Resources
  - group: MO Shared Resources
  - group: MO das-apim-endpoints
  jobs:
  - template: ../pipeline-templates/job/arm-deploy.yml
    parameters:
      ServiceConnection: SFA-ASM-ModelOffice-ARM
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-FCS
      Environment: MO

  - template: ../pipeline-templates/job/deploy-api.yml
    parameters:
      DeploymentName: Deploy_FindApprenticeshipTraining
      Environment: MO
      ServiceConnection: SFA-ASM-ModelOffice-ARM
      AppServiceName: $(FindApprenticeshipTrainingOuterApiAppServiceName)
      DeploymentPackagePath: $(Pipeline.Workspace)/das-apim-endpoints-build/ApimEndpointsArtifacts/SFA.DAS.FindApprenticeshipTraining.Api.zip
      ApiVersionSetName: $(FindApprenticeshipTrainingOuterApiVersionSetName)
      ApiPath: $(FindApprenticeshipTrainingOuterApiPath)
      ApiBaseUrl: $(FindApprenticeshipTrainingOuterApiBaseUrl)
      ProductId: $(FindApprenticeshipTrainingProductId)
      ApplicationIdentifierUri: $(FindApprenticeshipTrainingOuterApiIdentifierUri)
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-FCS

- stage: Deploy_DEMO
  dependsOn: []
  displayName: Deploy to DEMO
  variables:
  - group: DevTest Management Resources
  - group: DEMO DevTest Shared Resources
  - group: DEMO das-apim-endpoints
  jobs:
  - template: ../pipeline-templates/job/arm-deploy.yml
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-CDS
      Environment: DEMO

  - template: ../pipeline-templates/job/deploy-api.yml
    parameters:
      DeploymentName: Deploy_FindApprenticeshipTraining
      Environment: DEMO
      ServiceConnection: SFA-DAS-DevTest-ARM
      AppServiceName: $(FindApprenticeshipTrainingOuterApiAppServiceName)
      DeploymentPackagePath: $(Pipeline.Workspace)/das-apim-endpoints-build/ApimEndpointsArtifacts/SFA.DAS.FindApprenticeshipTraining.Api.zip
      ApiVersionSetName: $(FindApprenticeshipTrainingOuterApiVersionSetName)
      ApiPath: $(FindApprenticeshipTrainingOuterApiPath)
      ApiBaseUrl: $(FindApprenticeshipTrainingOuterApiBaseUrl)
      ProductId: $(FindApprenticeshipTrainingProductId)
      ApplicationIdentifierUri: $(FindApprenticeshipTrainingOuterApiIdentifierUri)
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-CDS