trigger: none
pr: none

variables:
- group: Release Management Resources
- group: RELEASE das-apim-endpoints
- name: OuterApiObject
  value: $(VacanciesManageOuterApiObject)

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.57
    endpoint: SkillsFundingAgency
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/5.0.2
    endpoint: SkillsFundingAgency
  pipelines:
  - pipeline: das-apim-endpoints-build
    project: Digital Apprenticeship Service
    source: das-apim-endpoints (build)
    branch: master
  - pipeline: das-employer-config
    project: Digital Apprenticeship Service
    source: das-employer-config
    branch: master

stages:
- stage: Deploy_AT
  dependsOn: []
  displayName: Deploy to AT
  variables:
  - group: DevTest Management Resources
  - group: AT DevTest Shared Resources
  - group: AT das-apim-endpoints
  jobs:
  - template: ../pipeline-templates/job/arm-deploy-old.yml
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-CDS
      Environment: AT
      SchemaFilePath: $(VacanciesManageOuterApiSchemaFilePath)

  - template: ../pipeline-templates/job/deploy-api.yml
    parameters:
      DeploymentName: Deploy_VacanciesManage
      Environment: AT
      ServiceConnection: SFA-DAS-DevTest-ARM
      AppServiceName: $(VacanciesManageOuterApiAppServiceName)
      DeploymentPackagePath: $(Pipeline.Workspace)/das-apim-endpoints-build/ApimEndpointsArtifacts/SFA.DAS.Vacancies.Manage.Api.zip
      ApiVersionSetName: $(VacanciesManageOuterApiVersionSetName)
      ApiPath: $(VacanciesManageOuterApiPath)
      ApiBaseUrl: $(VacanciesManageOuterApiBaseUrl)
      ProductId: $(VacanciesManageProductId)
      ApplicationIdentifierUri: $(VacanciesManageOuterApiIdentifierUri)
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-CDS
      SandboxEnabled: $(VacanciesManageSandboxEnabled)

- stage: Deploy_TEST
  dependsOn: []
  displayName: Deploy to TEST
  variables:
  - group: DevTest Management Resources
  - group: TEST DevTest Shared Resources
  - group: TEST das-apim-endpoints
  jobs:
  - template: ../pipeline-templates/job/arm-deploy-old.yml
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-CDS
      Environment: TEST
      SchemaFilePath: $(VacanciesManageOuterApiSchemaFilePath)

  - template: ../pipeline-templates/job/deploy-api.yml
    parameters:
      DeploymentName: Deploy_VacanciesManage
      Environment: TEST
      ServiceConnection: SFA-DAS-DevTest-ARM
      AppServiceName: $(VacanciesManageOuterApiAppServiceName)
      DeploymentPackagePath: $(Pipeline.Workspace)/das-apim-endpoints-build/ApimEndpointsArtifacts/SFA.DAS.Vacancies.Manage.Api.zip
      ApiVersionSetName: $(VacanciesManageOuterApiVersionSetName)
      ApiPath: $(VacanciesManageOuterApiPath)
      ApiBaseUrl: $(VacanciesManageOuterApiBaseUrl)
      ProductId: $(VacanciesManageProductId)
      ApplicationIdentifierUri: $(VacanciesManageOuterApiIdentifierUri)
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-CDS
      SandboxEnabled: $(VacanciesManageSandboxEnabled)

- stage: Deploy_TEST2
  dependsOn: []
  displayName: Deploy to TEST2
  variables:
  - group: DevTest Management Resources
  - group: TEST2 DevTest Shared Resources
  - group: TEST2 das-apim-endpoints
  jobs:
  - template: ../pipeline-templates/job/arm-deploy-old.yml
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-CDS
      Environment: TEST2
      SchemaFilePath: $(VacanciesManageOuterApiSchemaFilePath)

  - template: ../pipeline-templates/job/deploy-api.yml
    parameters:
      DeploymentName: Deploy_VacanciesManage
      Environment: TEST2
      ServiceConnection: SFA-DAS-DevTest-ARM
      AppServiceName: $(VacanciesManageOuterApiAppServiceName)
      DeploymentPackagePath: $(Pipeline.Workspace)/das-apim-endpoints-build/ApimEndpointsArtifacts/SFA.DAS.Vacancies.Manage.Api.zip
      ApiVersionSetName: $(VacanciesManageOuterApiVersionSetName)
      ApiPath: $(VacanciesManageOuterApiPath)
      ApiBaseUrl: $(VacanciesManageOuterApiBaseUrl)
      ProductId: $(VacanciesManageProductId)
      ApplicationIdentifierUri: $(VacanciesManageOuterApiIdentifierUri)
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-CDS
      SandboxEnabled: $(VacanciesManageSandboxEnabled)

- stage: Deploy_PP
  dependsOn: []
  displayName: Deploy to PP
  variables:
  - group: PREPROD Management Resources
  - group: PREPROD Shared Resources
  - group: PREPROD das-apim-endpoints
  jobs:
  - template: ../pipeline-templates/job/arm-deploy-old.yml
    parameters:
      ServiceConnection: SFA-DIG-PreProd-ARM
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-FCS
      Environment: PP
      SchemaFilePath: $(VacanciesManageOuterApiSchemaFilePath)

  - template: ../pipeline-templates/job/deploy-api.yml
    parameters:
      DeploymentName: Deploy_VacanciesManage
      Environment: PP
      ServiceConnection: SFA-DIG-PreProd-ARM
      AppServiceName: $(VacanciesManageOuterApiAppServiceName)
      DeploymentPackagePath: $(Pipeline.Workspace)/das-apim-endpoints-build/ApimEndpointsArtifacts/SFA.DAS.Vacancies.Manage.Api.zip
      ApiVersionSetName: $(VacanciesManageOuterApiVersionSetName)
      ApiPath: $(VacanciesManageOuterApiPath)
      ApiBaseUrl: $(VacanciesManageOuterApiBaseUrl)
      ProductId: $(VacanciesManageProductId)
      ApplicationIdentifierUri: $(VacanciesManageOuterApiIdentifierUri)
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-FCS
      SandboxEnabled: $(VacanciesManageSandboxEnabled)

- stage: Deploy_PROD
  dependsOn: []
  displayName: Deploy to PROD
  variables:
  - group: PROD Management Resources
  - group: PROD Shared Resources
  - group: PROD das-apim-endpoints
  jobs:
  - template: ../pipeline-templates/job/arm-deploy-old.yml
    parameters:
      ServiceConnection: SFA-DIG-Prod-ARM
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-FCS
      Environment: PROD
      SchemaFilePath: $(VacanciesManageOuterApiSchemaFilePath)

  - template: ../pipeline-templates/job/deploy-api.yml
    parameters:
      DeploymentName: Deploy_VacanciesManage
      Environment: PROD
      ServiceConnection: SFA-DIG-Prod-ARM
      AppServiceName: $(VacanciesManageOuterApiAppServiceName)
      DeploymentPackagePath: $(Pipeline.Workspace)/das-apim-endpoints-build/ApimEndpointsArtifacts/SFA.DAS.Vacancies.Manage.Api.zip
      ApiVersionSetName: $(VacanciesManageOuterApiVersionSetName)
      ApiPath: $(VacanciesManageOuterApiPath)
      ApiBaseUrl: $(VacanciesManageOuterApiBaseUrl)
      ProductId: $(VacanciesManageProductId)
      ApplicationIdentifierUri: $(VacanciesManageOuterApiIdentifierUri)
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-FCS
      SandboxEnabled: $(VacanciesManageSandboxEnabled)

- stage: Deploy_MO
  dependsOn: []
  displayName: Deploy to MO
  variables:
  - group: MO Management Resources
  - group: MO Shared Resources
  - group: MO das-apim-endpoints
  jobs:
  - template: ../pipeline-templates/job/arm-deploy-old.yml
    parameters:
      ServiceConnection: SFA-ASM-ModelOffice-ARM
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-FCS
      Environment: MO
      SchemaFilePath: $(VacanciesManageOuterApiSchemaFilePath)

  - template: ../pipeline-templates/job/deploy-api.yml
    parameters:
      DeploymentName: Deploy_VacanciesManage
      Environment: MO
      ServiceConnection: SFA-ASM-ModelOffice-ARM
      AppServiceName: $(VacanciesManageOuterApiAppServiceName)
      DeploymentPackagePath: $(Pipeline.Workspace)/das-apim-endpoints-build/ApimEndpointsArtifacts/SFA.DAS.Vacancies.Manage.Api.zip
      ApiVersionSetName: $(VacanciesManageOuterApiVersionSetName)
      ApiPath: $(VacanciesManageOuterApiPath)
      ApiBaseUrl: $(VacanciesManageOuterApiBaseUrl)
      ProductId: $(VacanciesManageProductId)
      ApplicationIdentifierUri: $(VacanciesManageOuterApiIdentifierUri)
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-FCS
      SandboxEnabled: $(VacanciesManageSandboxEnabled)

- stage: Deploy_DEMO
  dependsOn: []
  displayName: Deploy to DEMO
  variables:
  - group: DevTest Management Resources
  - group: DEMO DevTest Shared Resources
  - group: DEMO das-apim-endpoints
  jobs:
  - template: ../pipeline-templates/job/arm-deploy-old.yml
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-CDS
      Environment: DEMO
      SchemaFilePath: $(VacanciesManageOuterApiSchemaFilePath)

  - template: ../pipeline-templates/job/deploy-api.yml
    parameters:
      DeploymentName: Deploy_VacanciesManage
      Environment: DEMO
      ServiceConnection: SFA-DAS-DevTest-ARM
      AppServiceName: $(VacanciesManageOuterApiAppServiceName)
      DeploymentPackagePath: $(Pipeline.Workspace)/das-apim-endpoints-build/ApimEndpointsArtifacts/SFA.DAS.Vacancies.Manage.Api.zip
      ApiVersionSetName: $(VacanciesManageOuterApiVersionSetName)
      ApiPath: $(VacanciesManageOuterApiPath)
      ApiBaseUrl: $(VacanciesManageOuterApiBaseUrl)
      ProductId: $(VacanciesManageProductId)
      ApplicationIdentifierUri: $(VacanciesManageOuterApiIdentifierUri)
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-CDS
      SandboxEnabled: $(VacanciesManageSandboxEnabled)
