trigger:
  batch: true
  branches:
    include:
      - "master"

pr: none

variables:
  - group: 'Prod Management Resources'
  - name: buildConfiguration
    value: 'release'

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/heads/master
    endpoint: "GitHub (SFA)"

jobs:
- job: 'CodeBuild'
  pool:
    name: 'DAS - Continuous Integration'
    demands: Agent.OS -equals Linux
  workspace:
    clean: all  
  steps:
  - task: UseGitVersion@5
    displayName: GitVersion
    inputs:
      versionSpec: 5.x
      useConfigFile: true
      configFilePath: GitVersion.yml

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: 'src/**/*.csproj'
      noCache: true

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: 'src/**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-restore'
      
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '**/*.UnitTests.csproj'
      arguments: '--configuration $(buildConfiguration) --no-build'
      
  - task: DotNetCoreCLI@2
    displayName: 'Acceptance Tests'
    inputs:
      command: test
      projects: '**/*.AcceptanceTests.csproj'
      arguments: '--configuration $(buildConfiguration) --no-build'

  - template: azure-pipelines-templates/dependency-check.yml@das-platform-building-blocks

  - task: DotNetCoreCLI@2
    displayName: 'Publish FAT Api'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/SFA.DAS.FindApprenticeshipTraining.Api/SFA.DAS.FindApprenticeshipTraining.Api.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

  - task: DotNetCoreCLI@2
    displayName: 'Publish Find Epao Api'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/SFA.DAS.FindEpao.Api/SFA.DAS.FindEpao.Api.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'      
      
  - task: DotNetCoreCLI@2
    displayName: 'Publish Reservations Api'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/SFA.DAS.Reservations.Api/SFA.DAS.Reservations.Api.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

  - task: DotNetCoreCLI@2
    displayName: 'Publish Employer Incentives Api'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/SFA.DAS.EmployerIncentives.Api/SFA.DAS.EmployerIncentives.Api.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'      

  - task: DotNetCoreCLI@2
    displayName: 'Publish Forecasting Api'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/SFA.DAS.Forecasting.Api/SFA.DAS.Forecasting.Api.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'


  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      Contents: |
        azure/**
      TargetFolder: '$(build.artifactstagingdirectory)/publish'
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)/publish'