trigger:
  batch: true
  branches:
    include:
      - "master"

pr: none

variables:
  - group: 'Prod Management Resources'
  - name: buildConfiguration
    value: 'release'

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/heads/master
    endpoint: "GitHub (SFA)"

jobs:
- job: 'CodeBuild'
  pool:
    name: 'DAS - Continuous Integration'
    demands: Agent.OS -equals Linux
  workspace:
    clean: all  
  steps:
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      Contents: |
        azure/**
      TargetFolder: '$(build.artifactstagingdirectory)/publish'
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)/publish'