//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.DAS.EmployerIncentives.UnitTests.Application.Services.CustomerEngagementFinanceServiceTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CustomerExperienceServiceResponses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomerExperienceServiceResponses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SFA.DAS.EmployerIncentives.UnitTests.Application.Services.CustomerEngagementFinan" +
                            "ceServiceTests.CustomerExperienceServiceResponses", typeof(CustomerExperienceServiceResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {        &quot;CaseID&quot;: &quot;AF940440005&quot;,        &quot;VendorType&quot;: &quot;EMPLOYER&quot;,        &quot;SubmittedVendorIdentifier&quot;: &quot;P0007983&quot;,        &quot;ApprenticeshipLegalEntityID&quot;: &quot;DW5T8V&quot;,        &quot;UKPRN&quot;: &quot;&quot;,        &quot;URN&quot;: &quot;114286&quot;,        &quot;VendorCompanyRegistrationNo&quot;: &quot;&quot;,        &quot;CaseType&quot;: &quot;Amend&quot;,        &quot;VendorName&quot;: &quot;&quot;,        &quot;CaseStatusReasons&quot;: [            {                &quot;Code&quot;: &quot;BANK_INVALID&quot;,                &quot;Text&quot;: &quot;The bank account submitted is not showing as a valid combination of sort code and account number, please [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VrfJson {
            get {
                return ResourceManager.GetString("VrfJson", resourceCulture);
            }
        }
    }
}
