openapi: 3.0.0
info:
  version: '1.0'
  title: Approved training external API for consumption from an authenticated consumer
  description: 'This service will provide a contract to the Data Collections team for consumption of approved training'
paths:
  /info:
    get:
      description: information regarding this API. The version will be returned
      security:
        - ApiKeyAuth: []  # Require API Key authentication
      responses:
        '200':
          $ref: '#/components/responses/infoResponse'
        '429':
          $ref: '#/components/responses/rateLimitExceededResponse'   
  
  /health:
    get:
      description: The system is fully ready to accept requests and all the dependencies are healthy
      security:
        - ApiKeyAuth: []  # Require API Key authentication
      responses:
        '200':
          $ref: '#/components/responses/healthCheckResponse'
        '503':
          $ref: '#/components/responses/healthCheckResponse'
        '429':
          $ref: '#/components/responses/rateLimitExceededResponse' 

  /providers/{ukprn}/academicyears/{academicyear}/training:
    post:
      summary: Create a new record in the AS service due to no match
      security:
        - ApiKeyAuth: []  # Require API Key authentication
      parameters:
        - name: ukprn
          in: path
          required: true
          description: The UK Provider Reference Number for the provider entering this learner
          schema:
            type: string
        - name: academicyear
          in: path
          required: true
          example: 2425
          schema:
            type: integer
      requestBody:
        $ref: '#/components/requestBodies/trainingRecordRequest'
      responses:
        '201':
          $ref: '#/components/responses/acceptedResponse'
        '400':
          $ref: '#/components/responses/badRequest'
        '401':
          $ref: '#/components/responses/unauthorized'  
  
  /providers/{ukprn}/academicyears/{academicyear}/training/{trainingKey}:
    delete:
      summary: Deletes a training record identified by this request for this provider
      security:
        - ApiKeyAuth: []  # Require API Key authentication
      parameters:
        - name: ukprn
          in: path
          required: true
          description: The UK Provider Reference Number for the provider entering this learner
          schema:
            type: string
        - name: academicyear
          in: path
          required: true
          example: 2425
          schema:
            type: integer
        - name: trainingKey
          in: path
          required: true
          description: The internal key for this learner on the AS
          schema:
            type: string
      responses:
        '201':
          $ref: '#/components/responses/acceptedResponse'
    put:
      summary: Updates the details of a list of approved training records
      security:
        - ApiKeyAuth: []  # Require API Key authentication
      parameters:
        - name: ukprn
          in: path
          required: true
          description: The UK Provider Reference Number for the provider entering this learner
          schema:
            type: string
        - name: academicyear
          in: path
          required: true
          example: 2425
          schema:
            type: integer
        - name: trainingKey
          in: path
          required: true
          description: The internal key for this learner on the AS
          schema:
            type: string
      requestBody:
        $ref: '#/components/requestBodies/trainingRecordRequest'
      responses:
        '201':
          $ref: '#/components/responses/acceptedResponse'
        '400':
          $ref: '#/components/responses/badRequest'
        '401':
          $ref: '#/components/responses/unauthorized'         
          
  /providers/{ukprn}/academicyears/{academicyear}/trainingIdentifiers:
    get:
      summary: Returns a paged list of trainingIdentifiers for this provider
      security:
        - ApiKeyAuth: []  # Require API Key authentication
      parameters:
        - name: ukprn
          in: path
          required: true
          description: The UK Provider Reference Number for the provider entering this learner
          schema:
            type: string
        - name: academicyear
          in: path
          required: true
          example: 2425
          schema:
            type: integer
        - name: page
          in: query
          required: false
          description: Default is 1
          schema:
            type: integer
        - name: pagesize
          in: query
          required: false
          example: 20
          description: Default is 20, can be between 10 and 100
          schema:
            type: integer
      responses:
        '200':
          $ref: '#/components/responses/pagedTrainingIdentifiersResponse'  
    
components:  
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Ocp-Apim-Subscription-Key
      description: "Enter your API key in the `Ocp-Apim-Subscription-Key` header."
  headers:
    location:
      schema:
        type: string
        format: url
        example: /providers/234324/learners/24321432
    X-RateLimit-Limit:
      description: The maximum number of requests allowed in a time window
      schema:
        type: integer
        example: 100
    X-RateLimit-Remaining:
      description: The number of requests remaining in the current time window
      schema:
        type: integer
        example: 99
    X-RateLimit-Reset:
      description: The time (in UNIX timestamp) when the rate limit resets
      schema:
        type: integer
        example: 1712345678
    Retry-After:
      description: The number of seconds to wait before making a new request
      schema:
        type: integer
        example: 60

  requestBodies:
    trainingRecordRequest:
      description: Details of an updated training
      required: true
      content:
        application/json:
          schema:
            type: array 
            items:
              oneOf:
              - $ref: "#/components/schemas/apprenticeshipTraining"
              - $ref: "#/components/schemas/shortApprenticeshipTraining"
              - $ref: "#/components/schemas/foundationApprenticeshipTraining"
              - $ref: "#/components/schemas/shortCourseTraining"
  responses:
    pagedTrainingIdentifiersResponse:
      description: A paged training response
      headers:
        Link:
          description: Pagination links (next, prev)
          schema:
            type: string
            format: url
          example: '<https://api.example.com/items?page=2>; rel="prev", <https://api.example.com/items?page=5>; rel="next"'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/pagedTrainingIdentifiers'

    rateLimitExceededResponse:
      description: Too many requests - rate limit exceeded
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Rate limit exceeded. Try again later."

    acceptedResponse:
      description: A resource has been accepted on the platform    
      content:
        application/json:
          schema:
            type: object
            properties:
              correlationId:
                type: string
    
    okResponse:
      description: OK
      content:
        text/plain:
          schema:
            type: string
            example: OK

    badRequest:
      description: A bad request was sent and validation of the payload failed
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/error'

    unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'

    healthCheckResponse:
      description: Results of a health check
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/healthcheckResults'

    infoResponse:
      description: Information response
      content:
        text/plain:
          schema:
            type: string
            example: Leaner data APIM for the training service - Version 3.0.2
            
  schemas:
    error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    
    pagedTrainingIdentifiers:
      type: object
      properties:
        training:
          type: array
          items:
              $ref: '#/components/schemas/trainingIdentifier'
        total:
          type: integer
          minimum: 0
        page: 
          type: integer
          minimum: 1
        pageSize: 
          type: integer
          minimum: 1
          maximum: 100
        totalPages: 
          type: integer
          minimum: 1
      required:
        - page
        - total
        - pageSize  
        - totalPages  
    
    healthcheckResults:
      type: array
      items:
        $ref: '#/components/schemas/healthcheck' 
  
    healthcheck:
      type: object
      properties:
        description: 
          type: string
        result: 
          type: string    

    trainingIdentifier:
      type: object
      properties:
        trainingKey:
          type: string
          format: uuid
        ukprn:
          type: integer
        uln:
          type: integer
        standardCode:
          type: integer
        academicYear:
          type: integer

    # common CoC header
    header:
      type: object
      properties:
        ukprn:
          type: string
        academicYear:
          type: integer
        trainingType:
          type: string
          enum:
          - apprenticeship
          - shortApprenticeship
          - foundationApprenticeship
          - moduleOfOccStandard
        consumerReference:
          description: A reference the consumer can set. This will aid remediation under production errors and should not be used as a system identifier 
          type: string
          
    # apprenticeship, short apprenticeship and foundation apprenticeship
    
    apprenticeshipTraining:
      type: object
      properties:
        header:
          $ref: "#/components/schemas/header"
        learner:
          type: object
          properties:
            uln:
              type: string
            firstname:
              type: string
            lastname:
              type: string
            dob:
              type: string
              format: date
            email:
              type: string
            care:
              type: object
              properties:
                careleaver:
                  type: boolean
                hasEhcp:
                  type: boolean
                employerConsent:
                  type: boolean
        delivery:
          type: object
          properties:
            onProgramme:
              type: object
              properties:
                standardCode:
                  type: integer
                learnerRef:
                  type: string
                agreementId:
                  type: string
                startDate:
                  type: string
                  format: date
                expectedEndDate:
                  type: string
                  format: date
                OffTheJobHours:
                  type: integer
                percentageOfTrainingLeft:
                  type: integer
                costs:
                  type: array
                  items:
                    type: object
                    properties:
                      trainingPrice:
                        type: number
                      epaoPrice:
                        type: number
                      fromDate:
                        type: string
                        format: date
                      reduction4Rpl:
                        type: integer
            englishAndMaths:
              type: array
              items:
                type: object
                properties:
                  startDate:
                    type: string
                    format: date
                  endDate:
                    type: string
                    format: date
                  courseCode:
                    type: integer
            trainingSupport:
              type: array
              items:
                type: object
                properties:
                  from:
                    type: string
                    format: date
                  to:
                    type: string
                    format: date
        status:
          type: object
          properties:
            status:
              type: string
              enum:
              - pending
              - started
              - withdrawn
              - complete
              - paused
            dateOfChange:
              type: string
              format: date
            reason:
              type: string

          
    foundationApprenticeshipTraining:
      description: This is the exact copy of a normal apprenticeship
      allOf:
      - $ref: "#/components/schemas/apprenticeshipTraining"
  
    shortApprenticeshipTraining:
      description: This is the exact copy of a normal apprenticeship
      allOf:
      - $ref: "#/components/schemas/apprenticeshipTraining"
   
    shortCourseTraining:
      type: object
      properties:
        header:
          $ref: "#/components/schemas/header"
        learner:
          type: object
          properties:
            uln:
              type: string
            firstname:
              type: string
            lastname:
              type: string
            dob:
              type: string
              format: date
            email:
              type: string
        delivery:
          type: object
          properties:
            onProgramme:
              type: object
              properties:
                larsCode:
                  type: integer
                learnerRef:
                  type: string
                agreementId:
                  type: string
                startDate:
                  type: string
                  format: date
                expectedEndDate:
                  type: string
                  format: date
                costs:
                  type: array
                  items:
                    type: object
                    properties:
                      trainingPrice:
                        type: number
        status:
          type: object
          properties:
            status:
              type: string
              enum:
              - pending
              - started
              - withdrawn
              - complete
            dateOfChange:
              type: string
              format: date
            reason:
              type: string
        
security:
  - ApiKeyAuth: []  # Apply API Key security globally