openapi: 3.0.0
info:
  version: '1.0'
  title: Approved Apprenticeships external API for consumption from an authenticated consumer
  description: 'This service will provide a contract to the Data Collections team for consumption of approved apprenticeships'
paths:
  /info:
    get:
      description: information regarding this API. The version will be returned
      security:
        - ApiKeyAuth: []  # Require API Key authentication
      responses:
        '200':
          $ref: '#/components/responses/infoResponse'
        '429':
          $ref: '#/components/responses/rateLimitExceededResponse'   
  /liveness:
    get:
      description: The system is responsive and accepting incoming requests; however, this endpoint does not perform a dependency check, so the system may not be fully ready to process requests correctly.
      security:
        - ApiKeyAuth: []  # Require API Key authentication
      responses:
        '200':
          $ref: '#/components/responses/okResponse'
        '429':
          $ref: '#/components/responses/rateLimitExceededResponse'
  /readiness:
    get:
      description: The system is fully ready to accept requests and all the dependencies are healthy
      security:
        - ApiKeyAuth: []  # Require API Key authentication
      responses:
        '200':
          $ref: '#/components/responses/healthCheckResponse'
        '503':
          $ref: '#/components/responses/healthCheckResponse'
        '429':
          $ref: '#/components/responses/rateLimitExceededResponse' 

  /providers/{ukprn}/academicyears/{academicyear}/apprenticeships:
    get:
      summary: Returns a paged list of apprenticeships for this provider
      security:
        - ApiKeyAuth: []  # Require API Key authentication
      parameters:
        - name: ukprn
          in: path
          required: true
          description: The UK Provider Reference Number for the provider entering this learner
          schema:
            type: string
        - name: academicyear
          in: path
          required: true
          example: 2425
          schema:
            type: integer
        - name: page
          in: query
          required: false
          description: Default is 1
          schema:
            type: integer
        - name: pagesize
          in: query
          required: false
          example: 20
          description: Default is 20, can be between 10 and 100
          schema:
            type: integer
      responses:
        '200':
          $ref: '#/components/responses/pagedApprenticeshipsResponse'  

components:  
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: "Enter your API key in the `X-API-Key` header."
  headers:
    location:
      schema:
        type: string
        format: url
        example: /providers/234324/leaners/24321432
    X-RateLimit-Limit:
      description: The maximum number of requests allowed in a time window
      schema:
        type: integer
        example: 100
    X-RateLimit-Remaining:
      description: The number of requests remaining in the current time window
      schema:
        type: integer
        example: 99
    X-RateLimit-Reset:
      description: The time (in UNIX timestamp) when the rate limit resets
      schema:
        type: integer
        example: 1712345678
    Retry-After:
      description: The number of seconds to wait before making a new request
      schema:
        type: integer
        example: 60

  responses:
    pagedApprenticeshipsResponse:
      description: A paged apprenticeship response
      headers:
        Link:
          description: Pagination links (next, prev, first, last)
          schema:
            type: string
            format: url
          example: '<https://api.example.com/items?page=2>; rel="next", <https://api.example.com/items?page=5>; rel="last"'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/pagedApprenticeships'

    rateLimitExceededResponse:
      description: Too many requests - rate limit exceeded
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Rate limit exceeded. Try again later."

    okResponse:
      description: OK
      content:
        text/plain:
          schema:
            type: string
            example: OK

    unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'

    healthCheckResponse:
      description: Results of a health check
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/healthcheckResults'

    infoResponse:
      description: Information response
      content:
        text/plain:
          schema:
            type: string
            example: Leaner data APIM for the apprenticeship service - Version 3.0.2

  schemas:
    error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    
    pagedApprenticeships:
      type: object
      properties:
        apprenticeships:
          type: array
          items:
              $ref: '#/components/schemas/apprenticeship'
        total:
          type: integer
          minimum: 0
        page: 
          type: integer
          minimum: 1
        pageSize: 
          type: integer
          minimum: 1
          maximum: 100
        totalPages: 
          type: integer
          minimum: 1
      required:
        - page
        - total
        - pageSize  
        - totalPages  
    
    healthcheckResults:
      type: array
      items:
        $ref: '#/components/schemas/healthcheck' 
  
    healthcheck:
      type: object
      properties:
        description: 
          type: string
        result: 
          type: string    
    
    apprenticeship:
      type: object
      properties:
        uln:
          type: integer

security:
  - ApiKeyAuth: []  # Apply API Key security globally