parameters:
  DeploymentName:
  DeploymentApprovals:  
  AppRoleAssignmentsServiceConnection:
  ResourceName:

jobs:
- deployment: ${{ parameters.DeploymentName }}
  dependsOn: DeployInfrastructure
  environment: ${{ parameters.DeploymentApprovals }}
  strategy:
    runOnce:
      deploy:
        steps:
        - template: azure-pipelines-templates/deploy/step/app-role-assignments.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.AppRoleAssignmentsServiceConnection }}
            ResourceName: ${{ parameters.ResourceName }}
            Tenant: $(Tenant)