parameters:
  SonarCloudProjectKey:
  TargetProjects:
  UnitTestProjects:
  PublishProject: 
  AcceptanceTestProjects:

jobs:
- job: CodeBuild
  pool:
    name: DAS - Continuous Integration Agents
  variables:
  - group: ESFA - SonarCloud
  - name: buildConfiguration
    value: release
  workspace:
    clean: all
  steps:
  - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

  - template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks
    parameters:
      SonarCloud: true
      SonarCloudProjectKey: ${{ parameters.SonarCloudProjectKey }}
      SonarCloudExtraProperties: sonar.cpd.exclusions=Shared/SFA.DAS.SharedOuterApi/Services/*Client.cs
      TargetProjects: ${{ parameters.TargetProjects }}
      UnitTestProjects: ${{ parameters.UnitTestProjects }}
      AcceptanceTestProjects: ${{ parameters.AcceptanceTestProjects }}
      RunAcceptanceTests: true

  - task: DotNetCoreCLI@2
    displayName: 'Publish Outer Api'
    inputs:
      command: publish
      publishWebProjects: false
      projects: ${{ parameters.PublishProject }}
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      Contents: |
        azure/**
      TargetFolder: '$(build.artifactstagingdirectory)/publish'
      OverWrite: true

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifact'
    inputs:
      targetPath: '$(build.artifactstagingdirectory)/publish'
      artifactName: 'ApimEndpointsArtifacts'
