parameters:
  ServiceConnection:
  AppRoleAssignmentsServiceConnection:
  Environment:
  AADGroupObjectIdArray:
  SchemaFilePath:
  ConfigurationSecrets:
  DeploymentName:
  AppServiceName:
  CustomHostName:
  AppServiceKeyVaultCertificateName:
  ConfigNames:
  DeploymentPackagePath:
  ApiVersionSetName:
  ApiPath:
  ApiBaseUrl:
  ProductId:
  ApplicationIdentifierUri:
  SandboxEnabled: $False
  AddXForwardedAuthorization: $False
  useProductAppInsights:
  CheckClientCert: $False
  MandateCheckClientCert: $False

jobs:
- deployment: DeployInfrastructure
  pool:
    name: DAS - APIM Continuous Deployment Agents
  environment: ${{ parameters.Environment }}
  workspace:
    clean: all
  variables:
    AppServiceName: ${{ parameters.AppServiceName }}
    AppServicePlanName: ${{ parameters.AppServicePlanName }}
    CustomHostName: ${{ parameters.CustomHostName }}
    ApimEndpointsSubnetResourceId:  ${{ parameters.ApimEndpointsSubnetResourceId }}
    AppServiceKeyVaultCertificateName: ${{ parameters.AppServiceKeyVaultCertificateName }}
    ConfigNames: ${{ parameters.ConfigNames }}
  strategy:
    runOnce:
      deploy:
        steps:
        - template: azure-pipelines-templates/deploy/step/wait-azure-devops-deployment.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            EnvironmentId: $(Environment.Id)
            PipelineName: $(Build.DefinitionName)
            RunId: $(Build.BuildId)
        - ${{ if eq(parameters.useProductAppInsights, 'True') }}:
          - template: azure-pipelines-templates/deploy/step/get-product-app-insights.yml@das-platform-building-blocks
            parameters:
              ServiceConnection: ${{ parameters.ServiceConnection }}
              AppInsightsResourceGroup: $(SharedEnvResourceGroup)
              AppInsightsName: $(ProductAppInsightsName)
              IsMultiRepoCheckout: true
        - ${{ if ne(parameters.useProductAppInsights, 'True') }}:
          - template: azure-pipelines-templates/deploy/step/arm-deploy.yml@das-platform-building-blocks
            parameters:
              Location: $(ResourceGroupLocation)
              ServiceConnection: ${{ parameters.ServiceConnection }}
              SubscriptionId: $(SubscriptionId)
              TemplatePath: $(Pipeline.Workspace)/ApimEndpointsArtifacts/azure/template.json
              ParametersPath: $(Pipeline.Workspace)/ApimEndpointsArtifacts/azure/template.parameters.json
              IsMultiRepoCheckout: true
              TemplateSecrets:
                LoggingRedisConnectionString: $(LoggingRedisConnectionString)
                ConfigurationStorageConnectionString: $(ConfigurationStorageConnectionString)
        - ${{ if eq(parameters.useProductAppInsights, 'True') }}:
          - template: azure-pipelines-templates/deploy/step/arm-deploy.yml@das-platform-building-blocks
            parameters:
              Location: $(ResourceGroupLocation)
              ServiceConnection: ${{ parameters.ServiceConnection }}
              SubscriptionId: $(SubscriptionId)
              TemplatePath: $(Pipeline.Workspace)/ApimEndpointsArtifacts/azure/template.json
              ParametersPath: $(Pipeline.Workspace)/ApimEndpointsArtifacts/azure/template.parameters.json
              IsMultiRepoCheckout: true
              TemplateSecrets:
                LoggingRedisConnectionString: $(LoggingRedisConnectionString)
                ConfigurationStorageConnectionString: $(ConfigurationStorageConnectionString)
                applicationInsightsConnectionString: $(applicationInsightsConnectionString)
        - template: azure-pipelines-templates/deploy/step/generate-config.yml@das-platform-building-blocks
          parameters:
            EnvironmentName: $(EnvironmentName)
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SourcePath: $(Pipeline.Workspace)/das-employer-config/Configuration/das-apim-endpoints
            StorageAccountName: $(ConfigurationStorageAccountName)
            StorageAccountResourceGroup: $(SharedEnvResourceGroup)
            TargetFileName: ${{ parameters.SchemaFilePath }}
            TableName: Configuration
            ConfigurationSecrets: ${{ parameters.ConfigurationSecrets }}
        - template: azure-pipelines-templates/deploy/step/app-role-assignments.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.AppRoleAssignmentsServiceConnection }}
            ResourceName: ${{ parameters.AppServiceName }}
            Tenant: $(Tenant)
            AADGroupObjectIdArray: ${{ parameters.AADGroupObjectIdArray }}
            IsMultiRepoCheckout: true
        - template: azure-pipelines-templates/deploy/step/app-deploy.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            AppServiceName: ${{ parameters.AppServiceName }}
            DeploymentPackagePath: ${{ parameters.DeploymentPackagePath }}
        - checkout: das-platform-automation
        - task: AzurePowerShell@5
          displayName: Import-ApimSwaggerApiDefinition - ${{ parameters.AppServiceName }}
          inputs:
            azureSubscription: ${{ parameters.ServiceConnection }}
            ScriptPath: das-platform-automation/Infrastructure-Scripts/Import-ApimSwaggerApiDefinition.ps1
            ScriptArguments:
              -ApimResourceGroup $(ApimResourceGroup) `
              -InstanceName $(InstanceName) `
              -AppServiceResourceGroup $(ResourceGroupName) `
              -ApiVersionSetName ${{ parameters.ApiVersionSetName }} `
              -ApiPath ${{ parameters.ApiPath }} `
              -ApiBaseUrl ${{ parameters.ApiBaseUrl }} `
              -ProductId ${{ parameters.ProductId }} `
              -ApplicationIdentifierUri ${{ parameters.ApplicationIdentifierUri }} `
              -SandboxEnabled ${{ parameters.SandboxEnabled }} `
              -AddXForwardedAuthorization ${{ parameters.AddXForwardedAuthorization }} `
              -CheckClientCert ${{ parameters.CheckClientCert }} `
              -MandateCheckClientCert ${{ parameters.MandateCheckClientCert }} `
              -ApimKeyVaultUri $(ApimKeyVaultUri) `
              -ApimKeyVaultClientCertName $(ApimKeyVaultClientCertName) `
              -Verbose
            azurePowerShellVersion: LatestVersion
            pwsh: true
