parameters:
  ServiceConnection:
  Environment: AT
  
jobs:
- job: tests
  workspace:
    clean:
  pool:
    vmImage: ubuntu-latest
  steps:
    - checkout: self
      fetchDepth: 1
    # - template: azure-pipelines-templates/deploy/step/get-apim-subscription-key.yml@das-platform-building-blocks
    #   parameters:
    #     ServiceConnection: ${{ parameters.ServiceConnection }}
    #     ApimResourceGroup: $(SharedApimResourceGroup)
    #     ApimName: $(SharedApimName)
    #     SubscriptionId: $(AppServiceName)
    #     PipelineVariableName: ApprovalsApimSubscriptionKey
    #     IsMultiRepoCheckout: true
    - task: Bash@3
      inputs:
        targetType: inline
        script: |
          ls
    # - task: Bash@3
    #   inputs:
    #     targetType: inline
    #     script: |
    #       sed -i 's/<subscriptionKey>/$(subscriptionKey)/g' http-client.env.json
    #       ./HttpScripts/http-to-curl.js ./HttpScripts/CreateCandidateAndSubmitApplication.http --env=${{ parameters.Environment }} --out ./HttpScripts/generated.sh --exec
    # - bash: 
