parameters:
  Environment: AT
  OuterApiName:
  ServiceConnection:
  SubscriptionId:
  
jobs:
- job: tests
  workspace:
    clean:
  pool:
    vmImage: ubuntu-latest
  steps:
    - checkout: self
      fetchDepth: 1
    - template: azure-pipelines-templates/deploy/step/get-apim-subscription-key.yml@das-platform-building-blocks
      parameters:
        ServiceConnection: ${{ parameters.ServiceConnection }}
        ApimResourceGroup: $(SharedApimResourceGroup)
        ApimName: $(SharedApimName)
        SubscriptionId: ${{ parameters.SubscriptionId }}
        PipelineVariableName: ApimSubscriptionKey
        IsMultiRepoCheckout: true
    - task: Bash@3
      inputs:
        targetType: inline
        script: |
          sed -i 's/<subscriptionKey>/$(ApimSubscriptionKey)/g' http-client.env.json
          node ./src/${{ parameters.OuterApiName }}/SFA.DAS.${{ parameters.OuterApiName }}.UnitTests/HttpScripts/http-to-curl.js ./HttpScripts/CreateCandidateAndSubmitApplication.http --env=AT --out ./HttpScripts/generated.sh --exec
