parameters:
  Environment: AT
  OuterApiName:
  ServiceConnection:
  SubscriptionId:
  
jobs:
- job: tests
  displayName: Integration Tests
  workspace:
    clean:
  pool:
    vmImage: ubuntu-latest
  steps:
    - task: DownloadPipelineArtifact@2
    - checkout: self
    - template: azure-pipelines-templates/deploy/step/get-apim-subscription-key.yml@das-platform-building-blocks
      parameters:
        ServiceConnection: ${{ parameters.ServiceConnection }}
        ApimResourceGroup: $(SharedApimResourceGroup)
        ApimName: $(SharedApimName)
        SubscriptionId: ${{ parameters.SubscriptionId }}
        PipelineVariableName: ApimSubscriptionKey
        IsMultiRepoCheckout: true
    - task: Bash@3
      displayName: Run Tests
      inputs:
        targetType: inline
        script: |
          sed -i 's/<subscriptionKey>/$(ApimSubscriptionKey)/g' ./HttpScripts/http-client.env.json
          node ./HttpScripts/http-to-curl.js ./HttpScripts/CreateCandidateAndSubmitApplication.http --env=AT --out ./HttpScripts/generated.sh --exec
        workingDirectory: $(Pipeline.Workspace)/ApimEndpointsArtifacts/src/${{ parameters.OuterApiName }}/SFA.DAS.${{ parameters.OuterApiName }}.UnitTests/
