parameters:
  ServiceConnection:
  
jobs:
- job: tests
  pool:
    name: DAS - APIM Continuous Deployment Agents
  steps:
    # - template: azure-pipelines-templates/deploy/step/get-apim-subscription-key.yml@das-platform-building-blocks
    #   parameters:
    #     ServiceConnection: ${{ parameters.ServiceConnection }}
    #     ApimResourceGroup: $(SharedApimResourceGroup)
    #     ApimName: $(SharedApimName)
    #     SubscriptionId: $(AppServiceName)
    #     PipelineVariableName: ApprovalsApimSubscriptionKey
    #     IsMultiRepoCheckout: true
    
    - bash: ls
    # - bash: ./HttpScripts/http-to-curl.js ./HttpScripts/CreateCandidateAndSubmitApplication.http --env=dev --out ./HttpScripts/generated.sh --exec
