parameters:
  ServiceConnection:
  Environment:
  SchemaFilePath:

jobs:
- deployment: DeployInfrastructure
  pool:
    name: DAS - Continuous Deployment Agents
  environment: ${{ parameters.Environment }}
  workspace:
    clean: all
  strategy:
    runOnce:
      deploy:
        steps:
        - template: azure-pipelines-templates/deploy/step/arm-deploy.yml@das-platform-building-blocks
          parameters:
            Location: $(ResourceGroupLocation)
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SubscriptionId: $(SubscriptionId)
            TemplatePath: $(Pipeline.Workspace)/das-apim-endpoints-build/ApimEndpointsArtifacts/azure/shared-infrastructure-template.json
            ParametersPath: $(Pipeline.Workspace)/das-apim-endpoints-build/ApimEndpointsArtifacts/azure/shared-infrastructure-template.parameters.json
            IsMultiRepoCheckout: true