trigger:
  batch: true
  branches:
    include:
      - "master"
  paths:
    include:
    - azure
    - pipeline-templates
    - deployments
    - src/Approvals

pr:
  autoCancel: true
  branches:
    include:
      - "master"
  paths:
    include:
    - azure
    - pipeline-templates
    - deployments
    - src/Approvals
    - Directory.Packages.props

variables:
- group: Release Management Resources
- group: RELEASE das-apim-endpoints
- name: ProductShortName
  value: ea

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/3.0.6
    endpoint: SkillsFundingAgency
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/5.1.19
    endpoint: SkillsFundingAgency
  pipelines:
  - pipeline: das-employer-config
    project: Digital Apprenticeship Service
    source: das-employer-config
    branch: master

stages:
- template: ../../pipeline-templates/stage/outerapi-pipeline.yml
  parameters:
    OuterApiName: Approvals
    AddXForwardedAuthorization: $True
    useProductAppInsights: 'True'

- stage: TriggerSmokeTest
  dependsOn: Deploy_PROD
  displayName: Trigger Live Smoke Test 
  condition: succeeded()
  variables:
    - group: LIVE Shared Resources
  jobs:  
    - template: azure-pipelines-templates/deploy/job/trigger-live-smoke-test.yml@das-platform-building-blocks
      parameters:
        ServiceConnection: SFA-DIG-Prod-ARM