trigger:
  batch: true
  branches:
    include:
      - "master"
  paths:
    include:
    - azure
    - pipeline-templates
    - deployments
    - src/Approvals

pr:
  autoCancel: true
  branches:
    include:
      - "master"
  paths:
    include:
    - azure
    - pipeline-templates
    - deployments
    - src/Approvals
    - Directory.Packages.props

variables:
- group: Release Management Resources
- group: RELEASE das-apim-endpoints
- name: ProductShortName
  value: ea

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/2.2.20
    endpoint: SkillsFundingAgency
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/5.1.15
    endpoint: SkillsFundingAgency
  pipelines:
  - pipeline: das-employer-config
    project: Digital Apprenticeship Service
    source: das-employer-config
    branch: master

stages:
- template: ../../pipeline-templates/stage/outerapi-pipeline.yml
  parameters:
    OuterApiName: Approvals
    AddXForwardedAuthorization: $True
    useProductAppInsights: 'True'
